"""P1 ,P2 需求落地

Revision ID: 4298f2223457
Revises: 20250412_0002
Create Date: 2026-04-12 23:35:50.462984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4298f2223457'
down_revision: Union[str, None] = '20250412_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_constraint(op.f('projects_code_key'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.drop_constraint(op.f('standard_parts_code_key'), 'standard_parts', type_='unique')
    op.create_index(op.f('ix_standard_parts_code'), 'standard_parts', ['code'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_standard_parts_code'), table_name='standard_parts')
    op.create_unique_constraint(op.f('standard_parts_code_key'), 'standard_parts', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.create_unique_constraint(op.f('projects_code_key'), 'projects', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
