"""数据参数

Revision ID: b5894b42461c
Revises: 20260420_0002
Create Date: 2026-04-20 21:34:21.924606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5894b42461c'
down_revision: Union[str, None] = '20260420_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plastic_materials_abbreviation'), table_name='plastic_materials')
    op.drop_table('plastic_materials')
    op.create_index(op.f('ix_field_knowledge_docs_related_standard_part_id'), 'field_knowledge_docs', ['related_standard_part_id'], unique=False)
    op.create_index(op.f('ix_field_support_tickets_drawing_version_id'), 'field_support_tickets', ['drawing_version_id'], unique=False)
    op.create_index(op.f('ix_field_support_tickets_selection_stub_id'), 'field_support_tickets', ['selection_stub_id'], unique=False)
    op.create_index(op.f('ix_field_trial_runs_drawing_version_id'), 'field_trial_runs', ['drawing_version_id'], unique=False)
    op.create_index(op.f('ix_field_trial_runs_standard_part_id'), 'field_trial_runs', ['standard_part_id'], unique=False)
    op.drop_index(op.f('ix_integration_sync_jobs_created_at'), table_name='integration_sync_jobs')
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_constraint(op.f('projects_code_key'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.drop_index(op.f('ix_rd_deliverables_project_id'), table_name='rd_deliverables')
    op.create_index(op.f('ix_rd_deliverables_research_project_id'), 'rd_deliverables', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_library_intakes_project_id'), table_name='rd_library_intakes')
    op.create_index(op.f('ix_rd_library_intakes_research_project_id'), 'rd_library_intakes', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_release_iterations_project_id'), table_name='rd_release_iterations')
    op.create_index(op.f('ix_rd_release_iterations_research_project_id'), 'rd_release_iterations', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_research_projects_parent'), table_name='rd_research_projects')
    op.drop_constraint(op.f('uq_rd_research_projects_code'), 'rd_research_projects', type_='unique')
    op.create_index(op.f('ix_rd_research_projects_code'), 'rd_research_projects', ['code'], unique=True)
    op.create_index(op.f('ix_rd_research_projects_parent_project_id'), 'rd_research_projects', ['parent_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_research_tasks_project_id'), table_name='rd_research_tasks')
    op.create_index(op.f('ix_rd_research_tasks_research_project_id'), 'rd_research_tasks', ['research_project_id'], unique=False)
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.drop_index(op.f('ix_sel_material_abbr'), table_name='sel_material')
    op.drop_constraint(op.f('uq_sel_nozzle_hot_runner_index'), 'sel_nozzle_config', type_='unique')
    op.drop_constraint(op.f('standard_parts_code_key'), 'standard_parts', type_='unique')
    op.create_index(op.f('ix_standard_parts_code'), 'standard_parts', ['code'], unique=True)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_standard_parts_code'), table_name='standard_parts')
    op.create_unique_constraint(op.f('standard_parts_code_key'), 'standard_parts', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_sel_nozzle_hot_runner_index'), 'sel_nozzle_config', ['hot_runner_id', 'nozzle_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sel_material_abbr'), 'sel_material', ['abbreviation'], unique=False)
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_rd_research_tasks_research_project_id'), table_name='rd_research_tasks')
    op.create_index(op.f('ix_rd_research_tasks_project_id'), 'rd_research_tasks', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_research_projects_parent_project_id'), table_name='rd_research_projects')
    op.drop_index(op.f('ix_rd_research_projects_code'), table_name='rd_research_projects')
    op.create_unique_constraint(op.f('uq_rd_research_projects_code'), 'rd_research_projects', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rd_research_projects_parent'), 'rd_research_projects', ['parent_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_release_iterations_research_project_id'), table_name='rd_release_iterations')
    op.create_index(op.f('ix_rd_release_iterations_project_id'), 'rd_release_iterations', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_library_intakes_research_project_id'), table_name='rd_library_intakes')
    op.create_index(op.f('ix_rd_library_intakes_project_id'), 'rd_library_intakes', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_rd_deliverables_research_project_id'), table_name='rd_deliverables')
    op.create_index(op.f('ix_rd_deliverables_project_id'), 'rd_deliverables', ['research_project_id'], unique=False)
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.create_unique_constraint(op.f('projects_code_key'), 'projects', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_integration_sync_jobs_created_at'), 'integration_sync_jobs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_field_trial_runs_standard_part_id'), table_name='field_trial_runs')
    op.drop_index(op.f('ix_field_trial_runs_drawing_version_id'), table_name='field_trial_runs')
    op.drop_index(op.f('ix_field_support_tickets_selection_stub_id'), table_name='field_support_tickets')
    op.drop_index(op.f('ix_field_support_tickets_drawing_version_id'), table_name='field_support_tickets')
    op.drop_index(op.f('ix_field_knowledge_docs_related_standard_part_id'), table_name='field_knowledge_docs')
    op.create_table('plastic_materials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('mold_temp_c_range', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('melt_temp_c_range', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('degrade_temp_min_c', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('molding_window_delta_c', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eject_temp_c_range', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crystallinity', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('moisture_24h_pct', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('viscosity', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('corrosion_to_metal', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ref_injection_pressure_mpa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dwell_time_min', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plastic_materials_pkey'))
    )
    op.create_index(op.f('ix_plastic_materials_abbreviation'), 'plastic_materials', ['abbreviation'], unique=True)
    # ### end Alembic commands ###
