"""热流道规格字段 ↔ 选型字典分类 code（sel_dict_category / sel_dict_item）。"""

from __future__ import annotations

# (code, 分类显示名, sort_order, [选项 label])
SEL_HRSPEC_DICT_SEED: list[tuple[str, str, int, list[str]]] = [
    ("hrspec_system_glue_storage", "系统存胶模数", 9100, ["X<1", "1<X<3", "3<X"]),
    ("hrspec_main_nozzle_heating", "主射咀加热", 9101, ["是", "否"]),
    ("hrspec_main_nozzle_body_material", "主射咀/热咀本体材质", 9102, ["FS136", "4CR13"]),
    ("hrspec_main_nozzle_heater", "主射咀加热器", 9103, ["EPM", "GPM", "MCM"]),
    ("hrspec_manifold_bridge", "分流板搭桥", 9104, ["是", "否"]),
    ("hrspec_manifold_material", "分流板材质", 9105, ["FS136", "4CR13", "SKD61", "DC53", "P20"]),
    ("hrspec_manifold_channel_diameter", "分流板流道直径", 9106, ["5.0", "6.0", "8.0", "10", "15", "22"]),
    ("hrspec_manifold_nozzle_connection", "分流板与热咀对接方式", 9107, ["M", "平压斜孔", "T"]),
    ("hrspec_manifold_expansion_calc", "分流板计算膨胀", 9108, ["是", "否"]),
    ("hrspec_manifold_plug", "分流板堵头", 9109, ["BALA", "镶件+BALA", "常规"]),
    ("hrspec_channel_direction_diagram", "流道走向示意图", 9110, ["默认", "按模流分析报告"]),
    (
        "hrspec_hot_nozzle_structure",
        "热咀结构",
        9111,
        [
            "SLT",
            "TOE",
            "SOE",
            "TLS",
            "OA",
            "PLT",
            "PLS",
            "SAC",
            "SLC",
            "TAC",
            "TLC",
            "SCC",
            "CC",
            "CCH",
            "CA",
            "CT",
            "CTC",
            "CS",
            "EVV",
            "SVV",
            "VV",
            "VA",
            "STVA",
            "STVL",
            "TVA",
            "TVL",
            "TVAP",
        ],
    ),
    ("hrspec_hot_nozzle_heater", "热咀加热器", 9112, ["EPM", "EPT", "GPM", "GPT", "MCM", "MCT"]),
    (
        "hrspec_gate_diameter",
        "浇口直径",
        9113,
        ["1.0", "1.2", "1.5", "2", "2.5", "3.0", "3.5", "4.0", "5.0", "6.0", "7.0"],
    ),
    ("hrspec_nozzle_core_material", "咀芯材质", 9114, ["SKD61", "铍铜", "钼合金", "钨铜", "DC53"]),
    ("hrspec_nozzle_core_coating", "咀芯涂层", 9115, ["Cr", "Ni", "Ti", "Ni+Cr"]),
    ("hrspec_nozzle_cap_material", "咀帽材质", 9116, ["SKD61", "钛合金", "Cr12MoV"]),
    ("hrspec_insulation_cap_material", "隔热帽材质", 9117, ["PI", "PEEK", "钛合金"]),
    ("hrspec_valve_pin_style", "阀针样式", 9118, ["S", "T"]),
    ("hrspec_valve_pin_material", "阀针材质", 9119, ["SKD61", "SKH51"]),
    (
        "hrspec_valve_pin_plating_process",
        "阀针镀层工艺",
        9120,
        ["TiN", "CrN", "ZrN", "DLC", "TiAlN", "CrAlN", "TiN+DLC", "TiSiN", "CrN+DLC"],
    ),
    ("hrspec_shipping_water_jacket", "出货运水套", 9121, ["是", "仅设计"]),
    ("hrspec_shipping_protective_sleeve", "出货保护套", 9122, ["是", "仅设计"]),
]

# sel_mold_hot_runner_spec 列名（存 UUID）→ 字典分类 code
HR_SPEC_DICT_COLUMN_TO_CATEGORY: dict[str, str] = {
    "system_glue_storage_modulus_id": "hrspec_system_glue_storage",
    "main_nozzle_heating_id": "hrspec_main_nozzle_heating",
    "main_nozzle_body_material_id": "hrspec_main_nozzle_body_material",
    "main_nozzle_heater_id": "hrspec_main_nozzle_heater",
    "manifold_bridge_id": "hrspec_manifold_bridge",
    "manifold_material_id": "hrspec_manifold_material",
    "manifold_channel_diameter_id": "hrspec_manifold_channel_diameter",
    "manifold_nozzle_connection_id": "hrspec_manifold_nozzle_connection",
    "manifold_expansion_calc_id": "hrspec_manifold_expansion_calc",
    "manifold_plug_id": "hrspec_manifold_plug",
    "channel_direction_diagram_id": "hrspec_channel_direction_diagram",
    "hot_nozzle_structure_id": "hrspec_hot_nozzle_structure",
    "hot_nozzle_heater_id": "hrspec_hot_nozzle_heater",
    "gate_diameter_id": "hrspec_gate_diameter",
    "nozzle_core_material_id": "hrspec_nozzle_core_material",
    "nozzle_core_coating_id": "hrspec_nozzle_core_coating",
    "nozzle_cap_material_id": "hrspec_nozzle_cap_material",
    "insulation_cap_material_id": "hrspec_insulation_cap_material",
    "valve_pin_style_id": "hrspec_valve_pin_style",
    "valve_pin_material_id": "hrspec_valve_pin_material",
    "valve_pin_plating_process_id": "hrspec_valve_pin_plating_process",
    "shipping_water_jacket_id": "hrspec_shipping_water_jacket",
    "shipping_protective_sleeve_id": "hrspec_shipping_protective_sleeve",
}

HRSPEC_CATEGORY_CODES: frozenset[str] = frozenset(HR_SPEC_DICT_COLUMN_TO_CATEGORY.values())
